### ISSUE TITLE
Determine icon for .pashm files

### ISSUE THREAD

**Issue by parsampsh** [pashmaklang/vscode-pashmak#1]
Hi. does anyone know that how to determine icon for the files in vscode extensions?
@sami2020pro

**Comment by sami2020pro** [comment]
I think **Extension Guides** - <a href="https://code.visualstudio.com/api/extension-guides/product-icon-theme">Product Icon Theme</a>

**Comment by parsampsh** [comment]
Thanks. i'll read this.
